version: '3'
services:

  subscription-mysql-db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Subscription
      MYSQL_USER: subsvc
      MYSQL_PASSWORD: subsvc
    container_name: subscription-mysql-db
    restart: always

  subscription-service:
    build: .
    ports:
      - "8089:8089"
    container_name: subscription-service
    restart: always
    depends_on:
      - subscription-mysql-db