INSERT INTO PRODUCT (productId, name, description, trainingLevel, price, status, durationInWeeks) VALUES (1, 'Yoga Basics', 'Full-Body Yoga for Beginners', 'Easy', 400.00, true, 15)
INSERT INTO PRODUCT (productId, name, description, trainingLevel, price, status, durationInWeeks) VALUES (2, 'Get In Shape', 'A Mix of Cardio and Full-Body Toning', 'Medium', 367.00, true, 10)
INSERT INTO PRODUCT (productId, name, description, trainingLevel, price, status, durationInWeeks) VALUES (3, 'Pure Pilates', 'Holistic Training for Posture and Movement', 'Easy', 290.00, true, 8)
INSERT INTO PRODUCT (productId, name, description, trainingLevel, price, status, durationInWeeks) VALUES (4, 'Fat Burner', 'Fat-Burning Workouts to Get You Lean', 'Medium', 280.00, true, 6)
INSERT INTO PRODUCT (productId, name, description, trainingLevel, price, status, durationInWeeks) VALUES (5, 'Body Shape', 'Total-Body Toning', 'Medium', 310.00, true, 12)
INSERT INTO PRODUCT (productId, name, description, trainingLevel, price, status, durationInWeeks) VALUES (6, 'Six Pack', 'Core Strength Training for Sculpted Abs', 'Hard', 430.00, true, 12)
INSERT INTO PRODUCT (productId, name, description, trainingLevel, price, status, durationInWeeks) VALUES (7, 'Yoga Recover', 'Calming and Relaxing Restorative Yoga Flows', 'Easy', 180.00, true, 6)
INSERT INTO PRODUCT (productId, name, description, trainingLevel, price, status, durationInWeeks) VALUES (8, 'Full Body Circuit', 'Full-Body Dumbbell Circuit Training for Beginners', 'Easy', 384.00, true, 9)
INSERT INTO PRODUCT (productId, name, description, trainingLevel, price, status, durationInWeeks) VALUES (9, 'Mobility', 'Dynamic Stretches to Increase Flexibility and Mobility', 'Medium', 340.00, true, 7)
INSERT INTO PRODUCT (productId, name, description, trainingLevel, price, status, durationInWeeks) VALUES (10, 'Full-Body Starter', 'A 4-Week Program Perfect for Beginners', 'Easy', 130.00, true, 4)


INSERT INTO Customer (customerId, name, email, password, phone, address, active, role) VALUES (1, 'Donald Duck', 'donald@gmail.com', 'duck', '7866554422', '230, West road, Berlin', true, 'ROLE_CUSTOMER')
INSERT INTO Customer (customerId, name, email, password, phone, address, active, role) VALUES (2, 'Leonardo D', 'leo@gmail.com', 'caprio', '7866554422', '230, West road, Berlin', true, 'ROLE_USER')
INSERT INTO Customer (customerId, name, email, password, phone, address, active, role) VALUES (3, 'Tom Cruise', 'tom@gmail.com', 'mission', '7866554422', '230, West road, Berlin', true, 'ROLE_CUSTOMER')
INSERT INTO Customer (customerId, name, email, password, phone, address, active, role) VALUES (4, 'Robin Goodman', 'robin@gmail.com', 'batman', '7866554422', '230, West road, Berlin', true, 'ROLE_CUSTOMER')